package eulerProject61to90;

public class Problem89 {
	public static String decimalToRoman(int input) {
		String toReturn = "";
		for (; input >= 1000; input -= 1000) {
			toReturn += "M";
		}
		if (input >= 900) {
			toReturn += "CM";
			input -= 900;
		} else if (input >= 400 && input < 500) {
			toReturn += "CD";
			input -= 400;
		} else {
			if (input >= 500) {
				toReturn += "D";
				input -= 500;
			}
			for (; input >= 100; input -= 100) {
				toReturn += "C";
			}
		}
		if (input >= 90) {
			toReturn += "XC";
			input -= 90;
		} else if (input >= 40 && input < 50) {
			toReturn += "XL";
			input -= 40;
		} else {
			if (input >= 50) {
				toReturn += "L";
				input -= 50;
			}
			for (; input >= 10; input -= 10) {
				toReturn += "X";
			}
		}
		if (input == 9) {
			toReturn += "IX";
		} else if (input == 4) {
			toReturn += "IV";
		} else {
			if (input >= 5) {
				toReturn += "V";
				input -= 5;
			}
			for (; input > 0; input--) {
				toReturn += "I";
			}
		}
		return toReturn;
	}
	
	public static int romanToDecimal(String input) {
		int toReturn = 0;
		for (; input.length() > 0; input = input.substring(1)) {
			char firstChar = input.charAt(0);
			if (firstChar == 'M') {
				toReturn += 1000;
			} else if (firstChar == 'D') {
				toReturn += 500;
			} else if (firstChar == 'C') {
				if (input.length() > 1) {
					char secondChar = input.charAt(1);
					if (secondChar == 'M') {
						toReturn += 900;
						input = input.substring(1);
					} else if (secondChar == 'D') {
						toReturn += 400;
						input = input.substring(1);
					} else {
						toReturn += 100;
					}
				} else {
					toReturn += 100;
				}
			} else if (firstChar == 'L') {
				toReturn += 50;
			} else if (firstChar == 'X') {
				if (input.length() > 1) {
					char secondChar = input.charAt(1);
					if (secondChar == 'C') {
						toReturn += 90;
						input = input.substring(1);
					} else if (secondChar == 'L') {
						toReturn += 40;
						input = input.substring(1);
					} else {
						toReturn += 10;
					}
				} else {
					toReturn += 10;
				}
			} else if (firstChar == 'V') {
				toReturn += 5;
			} else if (input.length() > 1) {
				char secondChar = input.charAt(1);
				if (secondChar == 'X') {
					toReturn += 9;
					input = input.substring(1);
				} else if (secondChar == 'V') {
					toReturn += 4;
					input = input.substring(1);
				} else {
					toReturn++;
				}
			} else {
				toReturn++;
			}
		}
		return toReturn;
	}
	
	public static int savedCharacterWithEfficiency(String input) {
		String efficientResult = decimalToRoman(romanToDecimal(input));
		return input.length() - efficientResult.length();
	}
	
	public static void main(String[] args) {
		String romanNumerals = "MMMMDCLXXII\r\n"
				+ "MMDCCCLXXXIII\r\n"
				+ "MMMDLXVIIII\r\n"
				+ "MMMMDXCV\r\n"
				+ "DCCCLXXII\r\n"
				+ "MMCCCVI\r\n"
				+ "MMMCDLXXXVII\r\n"
				+ "MMMMCCXXI\r\n"
				+ "MMMCCXX\r\n"
				+ "MMMMDCCCLXXIII\r\n"
				+ "MMMCCXXXVII\r\n"
				+ "MMCCCLXXXXIX\r\n"
				+ "MDCCCXXIIII\r\n"
				+ "MMCXCVI\r\n"
				+ "CCXCVIII\r\n"
				+ "MMMCCCXXXII\r\n"
				+ "MDCCXXX\r\n"
				+ "MMMDCCCL\r\n"
				+ "MMMMCCLXXXVI\r\n"
				+ "MMDCCCXCVI\r\n"
				+ "MMMDCII\r\n"
				+ "MMMCCXII\r\n"
				+ "MMMMDCCCCI\r\n"
				+ "MMDCCCXCII\r\n"
				+ "MDCXX\r\n"
				+ "CMLXXXVII\r\n"
				+ "MMMXXI\r\n"
				+ "MMMMCCCXIV\r\n"
				+ "MLXXII\r\n"
				+ "MCCLXXVIIII\r\n"
				+ "MMMMCCXXXXI\r\n"
				+ "MMDCCCLXXII\r\n"
				+ "MMMMXXXI\r\n"
				+ "MMMDCCLXXX\r\n"
				+ "MMDCCCLXXIX\r\n"
				+ "MMMMLXXXV\r\n"
				+ "MCXXI\r\n"
				+ "MDCCCXXXVII\r\n"
				+ "MMCCCLXVII\r\n"
				+ "MCDXXXV\r\n"
				+ "CCXXXIII\r\n"
				+ "CMXX\r\n"
				+ "MMMCLXIV\r\n"
				+ "MCCCLXXXVI\r\n"
				+ "DCCCXCVIII\r\n"
				+ "MMMDCCCCXXXIV\r\n"
				+ "CDXVIIII\r\n"
				+ "MMCCXXXV\r\n"
				+ "MDCCCXXXII\r\n"
				+ "MMMMD\r\n"
				+ "MMDCCLXIX\r\n"
				+ "MMMMCCCLXXXXVI\r\n"
				+ "MMDCCXLII\r\n"
				+ "MMMDCCCVIIII\r\n"
				+ "DCCLXXXIIII\r\n"
				+ "MDCCCCXXXII\r\n"
				+ "MMCXXVII\r\n"
				+ "DCCCXXX\r\n"
				+ "CCLXIX\r\n"
				+ "MMMXI\r\n"
				+ "MMMMCMLXXXXVIII\r\n"
				+ "MMMMDLXXXVII\r\n"
				+ "MMMMDCCCLX\r\n"
				+ "MMCCLIV\r\n"
				+ "CMIX\r\n"
				+ "MMDCCCLXXXIIII\r\n"
				+ "CLXXXII\r\n"
				+ "MMCCCCXXXXV\r\n"
				+ "MMMMDLXXXVIIII\r\n"
				+ "MMMDCCCXXI\r\n"
				+ "MMDCCCCLXXVI\r\n"
				+ "MCCCCLXX\r\n"
				+ "MMCDLVIIII\r\n"
				+ "MMMDCCCLIX\r\n"
				+ "MMMMCCCCXIX\r\n"
				+ "MMMDCCCLXXV\r\n"
				+ "XXXI\r\n"
				+ "CDLXXXIII\r\n"
				+ "MMMCXV\r\n"
				+ "MMDCCLXIII\r\n"
				+ "MMDXXX\r\n"
				+ "MMMMCCCLVII\r\n"
				+ "MMMDCI\r\n"
				+ "MMMMCDLXXXIIII\r\n"
				+ "MMMMCCCXVI\r\n"
				+ "CCCLXXXVIII\r\n"
				+ "MMMMCML\r\n"
				+ "MMMMXXIV\r\n"
				+ "MMMCCCCXXX\r\n"
				+ "DCCX\r\n"
				+ "MMMCCLX\r\n"
				+ "MMDXXXIII\r\n"
				+ "CCCLXIII\r\n"
				+ "MMDCCXIII\r\n"
				+ "MMMCCCXLIV\r\n"
				+ "CLXXXXI\r\n"
				+ "CXVI\r\n"
				+ "MMMMCXXXIII\r\n"
				+ "CLXX\r\n"
				+ "DCCCXVIII\r\n"
				+ "MLXVII\r\n"
				+ "DLXXXX\r\n"
				+ "MMDXXI\r\n"
				+ "MMMMDLXXXXVIII\r\n"
				+ "MXXII\r\n"
				+ "LXI\r\n"
				+ "DCCCCXLIII\r\n"
				+ "MMMMDV\r\n"
				+ "MMMMXXXIV\r\n"
				+ "MDCCCLVIII\r\n"
				+ "MMMCCLXXII\r\n"
				+ "MMMMDCCXXXVI\r\n"
				+ "MMMMLXXXIX\r\n"
				+ "MDCCCLXXXI\r\n"
				+ "MMMMDCCCXV\r\n"
				+ "MMMMCCCCXI\r\n"
				+ "MMMMCCCLIII\r\n"
				+ "MDCCCLXXI\r\n"
				+ "MMCCCCXI\r\n"
				+ "MLXV\r\n"
				+ "MMCDLXII\r\n"
				+ "MMMMDXXXXII\r\n"
				+ "MMMMDCCCXL\r\n"
				+ "MMMMCMLVI\r\n"
				+ "CCLXXXIV\r\n"
				+ "MMMDCCLXXXVI\r\n"
				+ "MMCLII\r\n"
				+ "MMMCCCCXV\r\n"
				+ "MMLXXXIII\r\n"
				+ "MMMV\r\n"
				+ "MMMV\r\n"
				+ "DCCLXII\r\n"
				+ "MMDCCCCXVI\r\n"
				+ "MMDCXLVIII\r\n"
				+ "CCLIIII\r\n"
				+ "CCCXXV\r\n"
				+ "MMDCCLXXXVIIII\r\n"
				+ "MMMMDCLXXVIII\r\n"
				+ "MMMMDCCCXCI\r\n"
				+ "MMMMCCCXX\r\n"
				+ "MMCCXLV\r\n"
				+ "MMMDCCCLXIX\r\n"
				+ "MMCCLXIIII\r\n"
				+ "MMMDCCCXLIX\r\n"
				+ "MMMMCCCLXIX\r\n"
				+ "CMLXXXXI\r\n"
				+ "MCMLXXXIX\r\n"
				+ "MMCDLXI\r\n"
				+ "MMDCLXXVIII\r\n"
				+ "MMMMDCCLXI\r\n"
				+ "MCDXXV\r\n"
				+ "DL\r\n"
				+ "CCCLXXII\r\n"
				+ "MXVIIII\r\n"
				+ "MCCCCLXVIII\r\n"
				+ "CIII\r\n"
				+ "MMMDCCLXXIIII\r\n"
				+ "MMMDVIII\r\n"
				+ "MMMMCCCLXXXXVII\r\n"
				+ "MMDXXVII\r\n"
				+ "MMDCCLXXXXV\r\n"
				+ "MMMMCXLVI\r\n"
				+ "MMMDCCLXXXII\r\n"
				+ "MMMDXXXVI\r\n"
				+ "MCXXII\r\n"
				+ "CLI\r\n"
				+ "DCLXXXIX\r\n"
				+ "MMMCLI\r\n"
				+ "MDCLXIII\r\n"
				+ "MMMMDCCXCVII\r\n"
				+ "MMCCCLXXXV\r\n"
				+ "MMMDCXXVIII\r\n"
				+ "MMMCDLX\r\n"
				+ "MMMCMLII\r\n"
				+ "MMMIV\r\n"
				+ "MMMMDCCCLVIII\r\n"
				+ "MMMDLXXXVIII\r\n"
				+ "MCXXIV\r\n"
				+ "MMMMLXXVI\r\n"
				+ "CLXXIX\r\n"
				+ "MMMCCCCXXVIIII\r\n"
				+ "DCCLXXXV\r\n"
				+ "MMMDCCCVI\r\n"
				+ "LI\r\n"
				+ "CLXXXVI\r\n"
				+ "MMMMCCCLXXVI\r\n"
				+ "MCCCLXVI\r\n"
				+ "CCXXXIX\r\n"
				+ "MMDXXXXI\r\n"
				+ "MMDCCCXLI\r\n"
				+ "DCCCLXXXVIII\r\n"
				+ "MMMMDCCCIV\r\n"
				+ "MDCCCCXV\r\n"
				+ "MMCMVI\r\n"
				+ "MMMMCMLXXXXV\r\n"
				+ "MMDCCLVI\r\n"
				+ "MMMMCCXLVIII\r\n"
				+ "DCCCCIIII\r\n"
				+ "MMCCCCIII\r\n"
				+ "MMMDCCLXXXVIIII\r\n"
				+ "MDCCCLXXXXV\r\n"
				+ "DVII\r\n"
				+ "MMMV\r\n"
				+ "DCXXV\r\n"
				+ "MMDCCCXCV\r\n"
				+ "DCVIII\r\n"
				+ "MMCDLXVI\r\n"
				+ "MCXXVIII\r\n"
				+ "MDCCXCVIII\r\n"
				+ "MMDCLX\r\n"
				+ "MMMDCCLXIV\r\n"
				+ "MMCDLXXVII\r\n"
				+ "MMDLXXXIIII\r\n"
				+ "MMMMCCCXXII\r\n"
				+ "MMMDCCCXLIIII\r\n"
				+ "DCCCCLXVII\r\n"
				+ "MMMCLXXXXIII\r\n"
				+ "MCCXV\r\n"
				+ "MMMMDCXI\r\n"
				+ "MMMMDCLXXXXV\r\n"
				+ "MMMCCCLII\r\n"
				+ "MMCMIX\r\n"
				+ "MMDCCXXV\r\n"
				+ "MMDLXXXVI\r\n"
				+ "MMMMDCXXVIIII\r\n"
				+ "DCCCCXXXVIIII\r\n"
				+ "MMCCXXXIIII\r\n"
				+ "MMDCCLXXVIII\r\n"
				+ "MDCCLXVIIII\r\n"
				+ "MMCCLXXXV\r\n"
				+ "MMMMDCCCLXXXVIII\r\n"
				+ "MMCMXCI\r\n"
				+ "MDXLII\r\n"
				+ "MMMMDCCXIV\r\n"
				+ "MMMMLI\r\n"
				+ "DXXXXIII\r\n"
				+ "MMDCCXI\r\n"
				+ "MMMMCCLXXXIII\r\n"
				+ "MMMDCCCLXXIII\r\n"
				+ "MDCLVII\r\n"
				+ "MMCD\r\n"
				+ "MCCCXXVII\r\n"
				+ "MMMMDCCIIII\r\n"
				+ "MMMDCCXLVI\r\n"
				+ "MMMCLXXXVII\r\n"
				+ "MMMCCVIIII\r\n"
				+ "MCCCCLXXIX\r\n"
				+ "DL\r\n"
				+ "DCCCLXXVI\r\n"
				+ "MMDXCI\r\n"
				+ "MMMMDCCCCXXXVI\r\n"
				+ "MMCII\r\n"
				+ "MMMDCCCXXXXV\r\n"
				+ "MMMCDXLV\r\n"
				+ "MMDCXXXXIV\r\n"
				+ "MMD\r\n"
				+ "MDCCCLXXXX\r\n"
				+ "MMDCXLIII\r\n"
				+ "MMCCXXXII\r\n"
				+ "MMDCXXXXVIIII\r\n"
				+ "DCCCLXXI\r\n"
				+ "MDXCVIIII\r\n"
				+ "MMMMCCLXXVIII\r\n"
				+ "MDCLVIIII\r\n"
				+ "MMMCCCLXXXIX\r\n"
				+ "MDCLXXXV\r\n"
				+ "MDLVIII\r\n"
				+ "MMMMCCVII\r\n"
				+ "MMMMDCXIV\r\n"
				+ "MMMCCCLXIIII\r\n"
				+ "MMIIII\r\n"
				+ "MMMMCCCLXXIII\r\n"
				+ "CCIII\r\n"
				+ "MMMCCLV\r\n"
				+ "MMMDXIII\r\n"
				+ "MMMCCCXC\r\n"
				+ "MMMDCCCXXI\r\n"
				+ "MMMMCCCCXXXII\r\n"
				+ "CCCLVI\r\n"
				+ "MMMCCCLXXXVI\r\n"
				+ "MXVIIII\r\n"
				+ "MMMCCCCXIIII\r\n"
				+ "CLXVII\r\n"
				+ "MMMCCLXX\r\n"
				+ "CCCCLXIV\r\n"
				+ "MMXXXXII\r\n"
				+ "MMMMCCLXXXX\r\n"
				+ "MXL\r\n"
				+ "CCXVI\r\n"
				+ "CCCCLVIIII\r\n"
				+ "MMCCCII\r\n"
				+ "MCCCLVIII\r\n"
				+ "MMMMCCCX\r\n"
				+ "MCDLXXXXIV\r\n"
				+ "MDCCCXIII\r\n"
				+ "MMDCCCXL\r\n"
				+ "MMMMCCCXXIII\r\n"
				+ "DXXXIV\r\n"
				+ "CVI\r\n"
				+ "MMMMDCLXXX\r\n"
				+ "DCCCVII\r\n"
				+ "MMCMLXIIII\r\n"
				+ "MMMDCCCXXXIII\r\n"
				+ "DCCC\r\n"
				+ "MDIII\r\n"
				+ "MMCCCLXVI\r\n"
				+ "MMMCCCCLXXI\r\n"
				+ "MMDCCCCXVIII\r\n"
				+ "CCXXXVII\r\n"
				+ "CCCXXV\r\n"
				+ "MDCCCXII\r\n"
				+ "MMMCMV\r\n"
				+ "MMMMCMXV\r\n"
				+ "MMMMDCXCI\r\n"
				+ "DXXI\r\n"
				+ "MMCCXLVIIII\r\n"
				+ "MMMMCMLII\r\n"
				+ "MDLXXX\r\n"
				+ "MMDCLXVI\r\n"
				+ "CXXI\r\n"
				+ "MMMDCCCLIIII\r\n"
				+ "MMMCXXI\r\n"
				+ "MCCIII\r\n"
				+ "MMDCXXXXI\r\n"
				+ "CCXCII\r\n"
				+ "MMMMDXXXV\r\n"
				+ "MMMCCCLXV\r\n"
				+ "MMMMDLXV\r\n"
				+ "MMMCCCCXXXII\r\n"
				+ "MMMCCCVIII\r\n"
				+ "DCCCCLXXXXII\r\n"
				+ "MMCLXIV\r\n"
				+ "MMMMCXI\r\n"
				+ "MLXXXXVII\r\n"
				+ "MMMCDXXXVIII\r\n"
				+ "MDXXII\r\n"
				+ "MLV\r\n"
				+ "MMMMDLXVI\r\n"
				+ "MMMCXII\r\n"
				+ "XXXIII\r\n"
				+ "MMMMDCCCXXVI\r\n"
				+ "MMMLXVIIII\r\n"
				+ "MMMLX\r\n"
				+ "MMMCDLXVII\r\n"
				+ "MDCCCLVII\r\n"
				+ "MMCXXXVII\r\n"
				+ "MDCCCCXXX\r\n"
				+ "MMDCCCLXIII\r\n"
				+ "MMMMDCXLIX\r\n"
				+ "MMMMCMXLVIII\r\n"
				+ "DCCCLXXVIIII\r\n"
				+ "MDCCCLIII\r\n"
				+ "MMMCMLXI\r\n"
				+ "MMMMCCLXI\r\n"
				+ "MMDCCCLIII\r\n"
				+ "MMMDCCCVI\r\n"
				+ "MMDXXXXIX\r\n"
				+ "MMCLXXXXV\r\n"
				+ "MMDXXX\r\n"
				+ "MMMXIII\r\n"
				+ "DCLXXIX\r\n"
				+ "DCCLXII\r\n"
				+ "MMMMDCCLXVIII\r\n"
				+ "MDCCXXXXIII\r\n"
				+ "CCXXXII\r\n"
				+ "MMMMDCXXV\r\n"
				+ "MMMCCCXXVIII\r\n"
				+ "MDCVIII\r\n"
				+ "MMMCLXXXXIIII\r\n"
				+ "CLXXXI\r\n"
				+ "MDCCCCXXXIII\r\n"
				+ "MMMMDCXXX\r\n"
				+ "MMMDCXXIV\r\n"
				+ "MMMCCXXXVII\r\n"
				+ "MCCCXXXXIIII\r\n"
				+ "CXVIII\r\n"
				+ "MMDCCCCIV\r\n"
				+ "MMMMCDLXXV\r\n"
				+ "MMMDLXIV\r\n"
				+ "MDXCIII\r\n"
				+ "MCCLXXXI\r\n"
				+ "MMMDCCCXXIV\r\n"
				+ "MCXLIII\r\n"
				+ "MMMDCCCI\r\n"
				+ "MCCLXXX\r\n"
				+ "CCXV\r\n"
				+ "MMDCCLXXI\r\n"
				+ "MMDLXXXIII\r\n"
				+ "MMMMDCXVII\r\n"
				+ "MMMCMLXV\r\n"
				+ "MCLXVIII\r\n"
				+ "MMMMCCLXXVI\r\n"
				+ "MMMDCCLXVIIII\r\n"
				+ "MMMMDCCCIX\r\n"
				+ "DLXXXXIX\r\n"
				+ "DCCCXXII\r\n"
				+ "MMMMIII\r\n"
				+ "MMMMCCCLXXVI\r\n"
				+ "DCCCXCIII\r\n"
				+ "DXXXI\r\n"
				+ "MXXXIIII\r\n"
				+ "CCXII\r\n"
				+ "MMMDCCLXXXIIII\r\n"
				+ "MMMCXX\r\n"
				+ "MMMCMXXVII\r\n"
				+ "DCCCXXXX\r\n"
				+ "MMCDXXXVIIII\r\n"
				+ "MMMMDCCXVIII\r\n"
				+ "LV\r\n"
				+ "MMMDCCCCVI\r\n"
				+ "MCCCII\r\n"
				+ "MMCMLXVIIII\r\n"
				+ "MDCCXI\r\n"
				+ "MMMMDLXVII\r\n"
				+ "MMCCCCLXI\r\n"
				+ "MMDCCV\r\n"
				+ "MMMCCCXXXIIII\r\n"
				+ "MMMMDI\r\n"
				+ "MMMDCCCXCV\r\n"
				+ "MMDCCLXXXXI\r\n"
				+ "MMMDXXVI\r\n"
				+ "MMMDCCCLVI\r\n"
				+ "MMDCXXX\r\n"
				+ "MCCCVII\r\n"
				+ "MMMMCCCLXII\r\n"
				+ "MMMMXXV\r\n"
				+ "MMCMXXV\r\n"
				+ "MMLVI\r\n"
				+ "MMDXXX\r\n"
				+ "MMMMCVII\r\n"
				+ "MDC\r\n"
				+ "MCCIII\r\n"
				+ "MMMMDCC\r\n"
				+ "MMCCLXXV\r\n"
				+ "MMDCCCXXXXVI\r\n"
				+ "MMMMCCCLXV\r\n"
				+ "CDXIIII\r\n"
				+ "MLXIIII\r\n"
				+ "CCV\r\n"
				+ "MMMCMXXXI\r\n"
				+ "CCCCLXVI\r\n"
				+ "MDXXXII\r\n"
				+ "MMMMCCCLVIII\r\n"
				+ "MMV\r\n"
				+ "MMMCLII\r\n"
				+ "MCMLI\r\n"
				+ "MMDCCXX\r\n"
				+ "MMMMCCCCXXXVI\r\n"
				+ "MCCLXXXI\r\n"
				+ "MMMCMVI\r\n"
				+ "DCCXXX\r\n"
				+ "MMMMCCCLXV\r\n"
				+ "DCCCXI\r\n"
				+ "MMMMDCCCXIV\r\n"
				+ "CCCXXI\r\n"
				+ "MMDLXXV\r\n"
				+ "CCCCLXXXX\r\n"
				+ "MCCCLXXXXII\r\n"
				+ "MMDCIX\r\n"
				+ "DCCXLIIII\r\n"
				+ "DXIV\r\n"
				+ "MMMMCLII\r\n"
				+ "CDLXI\r\n"
				+ "MMMCXXVII\r\n"
				+ "MMMMDCCCCLXIII\r\n"
				+ "MMMDCLIIII\r\n"
				+ "MCCCCXXXXII\r\n"
				+ "MMCCCLX\r\n"
				+ "CCCCLIII\r\n"
				+ "MDCCLXXVI\r\n"
				+ "MCMXXIII\r\n"
				+ "MMMMDLXXVIII\r\n"
				+ "MMDCCCCLX\r\n"
				+ "MMMCCCLXXXX\r\n"
				+ "MMMCDXXVI\r\n"
				+ "MMMDLVIII\r\n"
				+ "CCCLXI\r\n"
				+ "MMMMDCXXII\r\n"
				+ "MMDCCCXXI\r\n"
				+ "MMDCCXIII\r\n"
				+ "MMMMCLXXXVI\r\n"
				+ "MDCCCCXXVI\r\n"
				+ "MDV\r\n"
				+ "MMDCCCCLXXVI\r\n"
				+ "MMMMCCXXXVII\r\n"
				+ "MMMDCCLXXVIIII\r\n"
				+ "MMMCCCCLXVII\r\n"
				+ "DCCXLI\r\n"
				+ "MMCLXXXVIII\r\n"
				+ "MCCXXXVI\r\n"
				+ "MMDCXLVIII\r\n"
				+ "MMMMCXXXII\r\n"
				+ "MMMMDCCLXVI\r\n"
				+ "MMMMCMLI\r\n"
				+ "MMMMCLXV\r\n"
				+ "MMMMDCCCXCIV\r\n"
				+ "MCCLXXVII\r\n"
				+ "LXXVIIII\r\n"
				+ "DCCLII\r\n"
				+ "MMMCCCXCVI\r\n"
				+ "MMMCLV\r\n"
				+ "MMDCCCXXXXVIII\r\n"
				+ "DCCCXV\r\n"
				+ "MXC\r\n"
				+ "MMDCCLXXXXVII\r\n"
				+ "MMMMCML\r\n"
				+ "MMDCCCLXXVIII\r\n"
				+ "DXXI\r\n"
				+ "MCCCXLI\r\n"
				+ "DCLXXXXI\r\n"
				+ "MMCCCLXXXXVIII\r\n"
				+ "MDCCCCLXXVIII\r\n"
				+ "MMMMDXXV\r\n"
				+ "MMMDCXXXVI\r\n"
				+ "MMMCMXCVII\r\n"
				+ "MMXVIIII\r\n"
				+ "MMMDCCLXXIV\r\n"
				+ "MMMCXXV\r\n"
				+ "DXXXVIII\r\n"
				+ "MMMMCLXVI\r\n"
				+ "MDXII\r\n"
				+ "MMCCCLXX\r\n"
				+ "CCLXXI\r\n"
				+ "DXIV\r\n"
				+ "MMMCLIII\r\n"
				+ "DLII\r\n"
				+ "MMMCCCXLIX\r\n"
				+ "MMCCCCXXVI\r\n"
				+ "MMDCXLIII\r\n"
				+ "MXXXXII\r\n"
				+ "CCCLXXXV\r\n"
				+ "MDCLXXVI\r\n"
				+ "MDCXII\r\n"
				+ "MMMCCCLXXXIII\r\n"
				+ "MMDCCCCLXXXII\r\n"
				+ "MMMMCCCLXXXV\r\n"
				+ "MMDCXXI\r\n"
				+ "DCCCXXX\r\n"
				+ "MMMDCCCCLII\r\n"
				+ "MMMDCCXXII\r\n"
				+ "MMMMCDXCVIII\r\n"
				+ "MMMCCLXVIIII\r\n"
				+ "MMXXV\r\n"
				+ "MMMMCDXIX\r\n"
				+ "MMMMCCCX\r\n"
				+ "MMMCCCCLXVI\r\n"
				+ "MMMMDCLXXVIIII\r\n"
				+ "MMMMDCXXXXIV\r\n"
				+ "MMMCMXII\r\n"
				+ "MMMMXXXIII\r\n"
				+ "MMMMDLXXXII\r\n"
				+ "DCCCLIV\r\n"
				+ "MDXVIIII\r\n"
				+ "MMMCLXXXXV\r\n"
				+ "CCCCXX\r\n"
				+ "MMDIX\r\n"
				+ "MMCMLXXXVIII\r\n"
				+ "DCCXLIII\r\n"
				+ "DCCLX\r\n"
				+ "D\r\n"
				+ "MCCCVII\r\n"
				+ "MMMMCCCLXXXIII\r\n"
				+ "MDCCCLXXIIII\r\n"
				+ "MMMDCCCCLXXXVII\r\n"
				+ "MMMMCCCVII\r\n"
				+ "MMMDCCLXXXXVI\r\n"
				+ "CDXXXIV\r\n"
				+ "MCCLXVIII\r\n"
				+ "MMMMDLX\r\n"
				+ "MMMMDXII\r\n"
				+ "MMMMCCCCLIIII\r\n"
				+ "MCMLXXXXIII\r\n"
				+ "MMMMDCCCIII\r\n"
				+ "MMDCLXXXIII\r\n"
				+ "MDCCCXXXXIV\r\n"
				+ "XXXXVII\r\n"
				+ "MMMDCCCXXXII\r\n"
				+ "MMMDCCCXLII\r\n"
				+ "MCXXXV\r\n"
				+ "MDCXXVIIII\r\n"
				+ "MMMCXXXXIIII\r\n"
				+ "MMMMCDXVII\r\n"
				+ "MMMDXXIII\r\n"
				+ "MMMMCCCCLXI\r\n"
				+ "DCLXXXXVIIII\r\n"
				+ "LXXXXI\r\n"
				+ "CXXXIII\r\n"
				+ "MCDX\r\n"
				+ "MCCLVII\r\n"
				+ "MDCXXXXII\r\n"
				+ "MMMCXXIV\r\n"
				+ "MMMMLXXXX\r\n"
				+ "MMDCCCCXLV\r\n"
				+ "MLXXX\r\n"
				+ "MMDCCCCLX\r\n"
				+ "MCDLIII\r\n"
				+ "MMMCCCLXVII\r\n"
				+ "MMMMCCCLXXIV\r\n"
				+ "MMMDCVIII\r\n"
				+ "DCCCCXXIII\r\n"
				+ "MMXCI\r\n"
				+ "MMDCCIV\r\n"
				+ "MMMMDCCCXXXIV\r\n"
				+ "CCCLXXI\r\n"
				+ "MCCLXXXII\r\n"
				+ "MCMIII\r\n"
				+ "CCXXXI\r\n"
				+ "DCCXXXVIII\r\n"
				+ "MMMMDCCXLVIIII\r\n"
				+ "MMMMCMXXXV\r\n"
				+ "DCCCLXXV\r\n"
				+ "DCCXCI\r\n"
				+ "MMMMDVII\r\n"
				+ "MMMMDCCCLXVIIII\r\n"
				+ "CCCXCV\r\n"
				+ "MMMMDCCXX\r\n"
				+ "MCCCCII\r\n"
				+ "MMMCCCXC\r\n"
				+ "MMMCCCII\r\n"
				+ "MMDCCLXXVII\r\n"
				+ "MMDCLIIII\r\n"
				+ "CCXLIII\r\n"
				+ "MMMDCXVIII\r\n"
				+ "MMMCCCIX\r\n"
				+ "MCXV\r\n"
				+ "MMCCXXV\r\n"
				+ "MLXXIIII\r\n"
				+ "MDCCXXVI\r\n"
				+ "MMMCCCXX\r\n"
				+ "MMDLXX\r\n"
				+ "MMCCCCVI\r\n"
				+ "MMDCCXX\r\n"
				+ "MMMMDCCCCXCV\r\n"
				+ "MDCCCXXXII\r\n"
				+ "MMMMDCCCCXXXX\r\n"
				+ "XCIV\r\n"
				+ "MMCCCCLX\r\n"
				+ "MMXVII\r\n"
				+ "MLXXI\r\n"
				+ "MMMDXXVIII\r\n"
				+ "MDCCCCII\r\n"
				+ "MMMCMLVII\r\n"
				+ "MMCLXXXXVIII\r\n"
				+ "MDCCCCLV\r\n"
				+ "MCCCCLXXIIII\r\n"
				+ "MCCCLII\r\n"
				+ "MCDXLVI\r\n"
				+ "MMMMDXVIII\r\n"
				+ "DCCLXXXIX\r\n"
				+ "MMMDCCLXIV\r\n"
				+ "MDCCCCXLIII\r\n"
				+ "CLXXXXV\r\n"
				+ "MMMMCCXXXVI\r\n"
				+ "MMMDCCCXXI\r\n"
				+ "MMMMCDLXXVII\r\n"
				+ "MCDLIII\r\n"
				+ "MMCCXLVI\r\n"
				+ "DCCCLV\r\n"
				+ "MCDLXX\r\n"
				+ "DCLXXVIII\r\n"
				+ "MMDCXXXIX\r\n"
				+ "MMMMDCLX\r\n"
				+ "MMDCCLI\r\n"
				+ "MMCXXXV\r\n"
				+ "MMMCCXII\r\n"
				+ "MMMMCMLXII\r\n"
				+ "MMMMCCV\r\n"
				+ "MCCCCLXIX\r\n"
				+ "MMMMCCIII\r\n"
				+ "CLXVII\r\n"
				+ "MCCCLXXXXIIII\r\n"
				+ "MMMMDCVIII\r\n"
				+ "MMDCCCLXI\r\n"
				+ "MMLXXIX\r\n"
				+ "CMLXIX\r\n"
				+ "MMDCCCXLVIIII\r\n"
				+ "DCLXII\r\n"
				+ "MMMCCCXLVII\r\n"
				+ "MDCCCXXXV\r\n"
				+ "MMMMDCCXCVI\r\n"
				+ "DCXXX\r\n"
				+ "XXVI\r\n"
				+ "MMLXIX\r\n"
				+ "MMCXI\r\n"
				+ "DCXXXVII\r\n"
				+ "MMMMCCCXXXXVIII\r\n"
				+ "MMMMDCLXI\r\n"
				+ "MMMMDCLXXIIII\r\n"
				+ "MMMMVIII\r\n"
				+ "MMMMDCCCLXII\r\n"
				+ "MDCXCI\r\n"
				+ "MMCCCXXIIII\r\n"
				+ "CCCCXXXXV\r\n"
				+ "MMDCCCXXI\r\n"
				+ "MCVI\r\n"
				+ "MMDCCLXVIII\r\n"
				+ "MMMMCXL\r\n"
				+ "MLXVIII\r\n"
				+ "CMXXVII\r\n"
				+ "CCCLV\r\n"
				+ "MDCCLXXXIX\r\n"
				+ "MMMCCCCLXV\r\n"
				+ "MMDCCLXII\r\n"
				+ "MDLXVI\r\n"
				+ "MMMCCCXVIII\r\n"
				+ "MMMMCCLXXXI\r\n"
				+ "MMCXXVII\r\n"
				+ "MMDCCCLXVIII\r\n"
				+ "MMMCXCII\r\n"
				+ "MMMMDCLVIII\r\n"
				+ "MMMMDCCCXXXXII\r\n"
				+ "MMDCCCCLXXXXVI\r\n"
				+ "MDCCXL\r\n"
				+ "MDCCLVII\r\n"
				+ "MMMMDCCCLXXXVI\r\n"
				+ "DCCXXXIII\r\n"
				+ "MMMMDCCCCLXXXV\r\n"
				+ "MMCCXXXXVIII\r\n"
				+ "MMMCCLXXVIII\r\n"
				+ "MMMDCLXXVIII\r\n"
				+ "DCCCI\r\n"
				+ "MMMMLXXXXVIIII\r\n"
				+ "MMMCCCCLXXII\r\n"
				+ "MMCLXXXVII\r\n"
				+ "CCLXVI\r\n"
				+ "MCDXLIII\r\n"
				+ "MMCXXVIII\r\n"
				+ "MDXIV\r\n"
				+ "CCCXCVIII\r\n"
				+ "CLXXVIII\r\n"
				+ "MMCXXXXVIIII\r\n"
				+ "MMMDCLXXXIV\r\n"
				+ "CMLVIII\r\n"
				+ "MCDLIX\r\n"
				+ "MMMMDCCCXXXII\r\n"
				+ "MMMMDCXXXIIII\r\n"
				+ "MDCXXI\r\n"
				+ "MMMDCXLV\r\n"
				+ "MCLXXVIII\r\n"
				+ "MCDXXII\r\n"
				+ "IV\r\n"
				+ "MCDLXXXXIII\r\n"
				+ "MMMMDCCLXV\r\n"
				+ "CCLI\r\n"
				+ "MMMMDCCCXXXVIII\r\n"
				+ "DCLXII\r\n"
				+ "MCCCLXVII\r\n"
				+ "MMMMDCCCXXXVI\r\n"
				+ "MMDCCXLI\r\n"
				+ "MLXI\r\n"
				+ "MMMCDLXVIII\r\n"
				+ "MCCCCXCIII\r\n"
				+ "XXXIII\r\n"
				+ "MMMDCLXIII\r\n"
				+ "MMMMDCL\r\n"
				+ "DCCCXXXXIIII\r\n"
				+ "MMDLVII\r\n"
				+ "DXXXVII\r\n"
				+ "MCCCCXXIIII\r\n"
				+ "MCVII\r\n"
				+ "MMMMDCCXL\r\n"
				+ "MMMMCXXXXIIII\r\n"
				+ "MCCCCXXIV\r\n"
				+ "MMCLXVIII\r\n"
				+ "MMXCIII\r\n"
				+ "MDCCLXXX\r\n"
				+ "MCCCLIIII\r\n"
				+ "MMDCLXXI\r\n"
				+ "MXI\r\n"
				+ "MCMLIV\r\n"
				+ "MMMCCIIII\r\n"
				+ "DCCLXXXVIIII\r\n"
				+ "MDCLIV\r\n"
				+ "MMMDCXIX\r\n"
				+ "CMLXXXI\r\n"
				+ "DCCLXXXVII\r\n"
				+ "XXV\r\n"
				+ "MMMXXXVI\r\n"
				+ "MDVIIII\r\n"
				+ "CLXIII\r\n"
				+ "MMMCDLVIIII\r\n"
				+ "MMCCCCVII\r\n"
				+ "MMMLXX\r\n"
				+ "MXXXXII\r\n"
				+ "MMMMCCCLXVIII\r\n"
				+ "MMDCCCXXVIII\r\n"
				+ "MMMMDCXXXXI\r\n"
				+ "MMMMDCCCXXXXV\r\n"
				+ "MMMXV\r\n"
				+ "MMMMCCXVIIII\r\n"
				+ "MMDCCXIIII\r\n"
				+ "MMMXXVII\r\n"
				+ "MDCCLVIIII\r\n"
				+ "MMCXXIIII\r\n"
				+ "MCCCLXXIV\r\n"
				+ "DCLVIII\r\n"
				+ "MMMLVII\r\n"
				+ "MMMCXLV\r\n"
				+ "MMXCVII\r\n"
				+ "MMMCCCLXXXVII\r\n"
				+ "MMMMCCXXII\r\n"
				+ "DXII\r\n"
				+ "MMMDLV\r\n"
				+ "MCCCLXXVIII\r\n"
				+ "MMMCLIIII\r\n"
				+ "MMMMCLXXXX\r\n"
				+ "MMMCLXXXIIII\r\n"
				+ "MDCXXIII\r\n"
				+ "MMMMCCXVI\r\n"
				+ "MMMMDLXXXIII\r\n"
				+ "MMMDXXXXIII\r\n"
				+ "MMMMCCCCLV\r\n"
				+ "MMMDLXXXI\r\n"
				+ "MMMCCLXXVI\r\n"
				+ "MMMMXX\r\n"
				+ "MMMMDLVI\r\n"
				+ "MCCCCLXXX\r\n"
				+ "MMMXXII\r\n"
				+ "MMXXII\r\n"
				+ "MMDCCCCXXXI\r\n"
				+ "MMMDXXV\r\n"
				+ "MMMDCLXXXVIIII\r\n"
				+ "MMMDLXXXXVII\r\n"
				+ "MDLXIIII\r\n"
				+ "CMXC\r\n"
				+ "MMMXXXVIII\r\n"
				+ "MDLXXXVIII\r\n"
				+ "MCCCLXXVI\r\n"
				+ "MMCDLIX\r\n"
				+ "MMDCCCXVIII\r\n"
				+ "MDCCCXXXXVI\r\n"
				+ "MMMMCMIV\r\n"
				+ "MMMMDCIIII\r\n"
				+ "MMCCXXXV\r\n"
				+ "XXXXVI\r\n"
				+ "MMMMCCXVII\r\n"
				+ "MMCCXXIV\r\n"
				+ "MCMLVIIII\r\n"
				+ "MLXXXIX\r\n"
				+ "MMMMLXXXIX\r\n"
				+ "CLXXXXIX\r\n"
				+ "MMMDCCCCLVIII\r\n"
				+ "MMMMCCLXXIII\r\n"
				+ "MCCCC\r\n"
				+ "DCCCLIX\r\n"
				+ "MMMCCCLXXXII\r\n"
				+ "MMMCCLXVIIII\r\n"
				+ "MCLXXXV\r\n"
				+ "CDLXXXVII\r\n"
				+ "DCVI\r\n"
				+ "MMX\r\n"
				+ "MMCCXIII\r\n"
				+ "MMMMDCXX\r\n"
				+ "MMMMXXVIII\r\n"
				+ "DCCCLXII\r\n"
				+ "MMMMCCCXLIII\r\n"
				+ "MMMMCLXV\r\n"
				+ "DXCI\r\n"
				+ "MMMMCLXXX\r\n"
				+ "MMMDCCXXXXI\r\n"
				+ "MMMMXXXXVI\r\n"
				+ "DCLX\r\n"
				+ "MMMCCCXI\r\n"
				+ "MCCLXXX\r\n"
				+ "MMCDLXXII\r\n"
				+ "DCCLXXI\r\n"
				+ "MMMCCCXXXVI\r\n"
				+ "MCCCCLXXXVIIII\r\n"
				+ "CDLVIII\r\n"
				+ "DCCLVI\r\n"
				+ "MMMMDCXXXVIII\r\n"
				+ "MMCCCLXXXIII\r\n"
				+ "MMMMDCCLXXV\r\n"
				+ "MMMXXXVI\r\n"
				+ "CCCLXXXXIX\r\n"
				+ "CV\r\n"
				+ "CCCCXIII\r\n"
				+ "CCCCXVI\r\n"
				+ "MDCCCLXXXIIII\r\n"
				+ "MMDCCLXXXII\r\n"
				+ "MMMMCCCCLXXXI\r\n"
				+ "MXXV\r\n"
				+ "MMCCCLXXVIIII\r\n"
				+ "MMMCCXII\r\n"
				+ "MMMMCCXXXIII\r\n"
				+ "MMCCCLXXXVI\r\n"
				+ "MMMDCCCLVIIII\r\n"
				+ "MCCXXXVII\r\n"
				+ "MDCLXXV\r\n"
				+ "XXXV\r\n"
				+ "MMDLI\r\n"
				+ "MMMCCXXX\r\n"
				+ "MMMMCXXXXV\r\n"
				+ "CCCCLIX\r\n"
				+ "MMMMDCCCLXXIII\r\n"
				+ "MMCCCXVII\r\n"
				+ "DCCCXVI\r\n"
				+ "MMMCCCXXXXV\r\n"
				+ "MDCCCCXCV\r\n"
				+ "CLXXXI\r\n"
				+ "MMMMDCCLXX\r\n"
				+ "MMMDCCCIII\r\n"
				+ "MMCLXXVII\r\n"
				+ "MMMDCCXXIX\r\n"
				+ "MMDCCCXCIIII\r\n"
				+ "MMMCDXXIIII\r\n"
				+ "MMMMXXVIII\r\n"
				+ "MMMMDCCCCLXVIII\r\n"
				+ "MDCCCXX\r\n"
				+ "MMMMCDXXI\r\n"
				+ "MMMMDLXXXIX\r\n"
				+ "CCXVI\r\n"
				+ "MDVIII\r\n"
				+ "MMCCLXXI\r\n"
				+ "MMMDCCCLXXI\r\n"
				+ "MMMCCCLXXVI\r\n"
				+ "MMCCLXI\r\n"
				+ "MMMMDCCCXXXIV\r\n"
				+ "DLXXXVI\r\n"
				+ "MMMMDXXXII\r\n"
				+ "MMMXXIIII\r\n"
				+ "MMMMCDIV\r\n"
				+ "MMMMCCCXLVIII\r\n"
				+ "MMMMCXXXVIII\r\n"
				+ "MMMCCCLXVI\r\n"
				+ "MDCCXVIII\r\n"
				+ "MMCXX\r\n"
				+ "CCCLIX\r\n"
				+ "MMMMDCCLXXII\r\n"
				+ "MDCCCLXXV\r\n"
				+ "MMMMDCCCXXIV\r\n"
				+ "DCCCXXXXVIII\r\n"
				+ "MMMDCCCCXXXVIIII\r\n"
				+ "MMMMCCXXXV\r\n"
				+ "MDCLXXXIII\r\n"
				+ "MMCCLXXXIV\r\n"
				+ "MCLXXXXIIII\r\n"
				+ "DXXXXIII\r\n"
				+ "MCCCXXXXVIII\r\n"
				+ "MMCLXXIX\r\n"
				+ "MMMMCCLXIV\r\n"
				+ "MXXII\r\n"
				+ "MMMCXIX\r\n"
				+ "MDCXXXVII\r\n"
				+ "MMDCCVI\r\n"
				+ "MCLXXXXVIII\r\n"
				+ "MMMCXVI\r\n"
				+ "MCCCLX\r\n"
				+ "MMMCDX\r\n"
				+ "CCLXVIIII\r\n"
				+ "MMMCCLX\r\n"
				+ "MCXXVIII\r\n"
				+ "LXXXII\r\n"
				+ "MCCCCLXXXI\r\n"
				+ "MMMI\r\n"
				+ "MMMCCCLXIV\r\n"
				+ "MMMCCCXXVIIII\r\n"
				+ "CXXXVIII\r\n"
				+ "MMCCCXX\r\n"
				+ "MMMCCXXVIIII\r\n"
				+ "MCCLXVI\r\n"
				+ "MMMCCCCXXXXVI\r\n"
				+ "MMDCCXCIX\r\n"
				+ "MCMLXXI\r\n"
				+ "MMCCLXVIII\r\n"
				+ "CDLXXXXIII\r\n"
				+ "MMMMDCCXXII\r\n"
				+ "MMMMDCCLXXXVII\r\n"
				+ "MMMDCCLIV\r\n"
				+ "MMCCLXIII\r\n"
				+ "MDXXXVII\r\n"
				+ "DCCXXXIIII\r\n"
				+ "MCII\r\n"
				+ "MMMDCCCLXXI\r\n"
				+ "MMMLXXIII\r\n"
				+ "MDCCCLIII\r\n"
				+ "MMXXXVIII\r\n"
				+ "MDCCXVIIII\r\n"
				+ "MDCCCCXXXVII\r\n"
				+ "MMCCCXVI\r\n"
				+ "MCMXXII\r\n"
				+ "MMMCCCLVIII\r\n"
				+ "MMMMDCCCXX\r\n"
				+ "MCXXIII\r\n"
				+ "MMMDLXI\r\n"
				+ "MMMMDXXII\r\n"
				+ "MDCCCX\r\n"
				+ "MMDXCVIIII\r\n"
				+ "MMMDCCCCVIII\r\n"
				+ "MMMMDCCCCXXXXVI\r\n"
				+ "MMDCCCXXXV\r\n"
				+ "MMCXCIV\r\n"
				+ "MCMLXXXXIII\r\n"
				+ "MMMCCCLXXVI\r\n"
				+ "MMMMDCLXXXV\r\n"
				+ "CMLXIX\r\n"
				+ "DCXCII\r\n"
				+ "MMXXVIII\r\n"
				+ "MMMMCCCXXX\r\n"
				+ "XXXXVIIII";
		int index = 0;
		long sum = 0;
		while (romanNumerals.contains("\n")) {
			if (romanNumerals.charAt(index) == '\r') {
				sum += savedCharacterWithEfficiency(romanNumerals.substring(0, index));
				romanNumerals = romanNumerals.substring(index + 2);
				index = 0;
			} else {
				index++;
			}
		}
		sum += savedCharacterWithEfficiency(romanNumerals);
		System.out.println("Ausgabe: " + sum);
	}
	
	/* Remark: I have no clue why the difficulty here is 20%. It's so damn easy, just takes a bit of time to do.
	 * Problem solved
	 * 23327th person to have solved this problem
	 * Difficulty rating: 20%
	 * Runtime: 1 second
	 * */
}
